# Import librairies + data

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

url = "https://raw.githubusercontent.com/JBaptisteAll/Japan_tourism_analysis/refs/heads/main/data_processed/df_clean.csv"

df = pd.read_csv(url)
print(df.shape)

(54, 42)

In [2]:
df.columns

Index(['Horodateur', 'nationality', 'country', 'age_group', 'family_situation',
       'household_income_in_€', 'travel_frequency', 'been_to_Japan',
       'Japan_vac_duration', 'rating_interest_culture_and_history',
       'rating_interest_food', 'rating_interest_nature_hiking',
       'rating_interest_shopping_and_techno',
       'rating_interest_events_and_festivals', 'rating_interest_wellness',
       'rating_interest_theme_park', 'Japan_budget_per_week',
       'Japan_prefered_accomodation', 'alternative_destination',
       'alt_dest_main_reason', 'alt_dest_prefered_accomodation',
       'alt_dest_budget_per_week', 'alt_dest_transportation', 'trip_prep',
       'booking_trip_channel', 'most_influencial_reason_to_choose_dest',
       'recomendation_to_improve_attractiveness',
       'most_wanted_pref_to_visit_1', 'most_wanted_pref_to_visit_2',
       'most_wanted_pref_to_visit_3', 'most_wanted_pref_to_visit_4',
       'most_wanted_pref_to_visit_5', 'Japan_most_difficulties_1',
       'Japan_most_difficulties_2', 'Japan_most_difficulties_3',
       'Japan_most_difficulties_4', 'Japan_most_difficulties_5',
       'alt_dest_most_difficulties_1', 'alt_dest_most_difficulties_2',
       'alt_dest_most_difficulties_3', 'alt_dest_most_difficulties_4',
       'alt_dest_most_difficulties_5'],
      dtype='object')

In [3]:
display(df.head())

,Horodateur,nationality,country,age_group,family_situation,household_income_in_€,travel_frequency,been_to_Japan,Japan_vac_duration,rating_interest_culture_and_history,...,Japan_most_difficulties_1,Japan_most_difficulties_2,Japan_most_difficulties_3,Japan_most_difficulties_4,Japan_most_difficulties_5,alt_dest_most_difficulties_1,alt_dest_most_difficulties_2,alt_dest_most_difficulties_3,alt_dest_most_difficulties_4,alt_dest_most_difficulties_5
0,05/10/2025 13:09:39,France,France,35-44,Married_no_kids,1500-1999,Every 2–3 years,"Yes, several times",More than 4 weeks,Essential,...,Language,Crowded/Popularity,Translation,NaN,NaN,Language,Transportation,Car rental,NaN,NaN
1,06/10/2025 13:30:50,France,France,45-54,Relationship_with_kids,1500-1999,Every 2–3 years,"No, but I would like to go",2 weeks,Essential,...,Language,Expensive,Translation,NaN,NaN,Expensive,Crowded,Translation,NaN,NaN
2,06/10/2025 17:20:05,France,France,35-44,Single,1500-1999,Once a year,"No, but I would like to go",3 weeks,Very important,...,Language,Car rental,Expensive,NaN,NaN,Language,Car rental,Expensive,NaN,NaN
3,06/10/2025 19:47:27,France,France,45-54,Single,2000-2499,Every 2–3 years,"No, but I would like to go",1 week,Moderately important,...,Car rental,Expensive,NaN,NaN,NaN,Transportation,NaN,NaN,NaN,NaN
4,06/10/2025 20:56:00,France,France,45-54,Married_no_kids,2500-2999,Every 2–3 years,"No, but I would like to go",3 weeks,Very important,...,Language,Expensive,NaN,NaN,NaN,Language,NaN,NaN,NaN,NaN

# Slide 2
## Overall people intersted about a trip to Japan

🎯 Constater un fort intérêt ne suffit pas.

Sur ce projet, près de 65 % des répondants n’ont jamais visité le Japon…    
mais déclarent clairement vouloir y aller.

🧠 Le problème n’était donc pas la notoriété.  
L’envie était déjà là.

📊 La vraie question était ailleurs :  
pourquoi autant de désir ne se transforme pas en passage à l’action ?

👉 Avant même d’analyser plus finement,  
il a fallu reformuler le problème :  
ce n’était pas une question d’intérêt,  
mais une question de conversion.

💬 Dans vos projets data, à quel moment prenez-vous le temps de reformuler le problème avant d’ouvrir le dataset ?

In [4]:
df_slide2 = df

In [5]:
mapping_xp_japan = {
    "Yes, several times": "Déjà allés",
    "Yes, once": "Déjà allés",
    "No, and I’m not interested": "Pas intéressés (jamais allés)",
    "No, but I would like to go": "Intéressés (jamais allés)"
}

df_slide2["been_to_Japan"] = (df["been_to_Japan"].map(mapping_xp_japan))

In [6]:
df_xp_japan = df_slide2["been_to_Japan"].value_counts().reset_index()

In [7]:
print(df_xp_japan)

                   been_to_Japan  count
0      Intéressés (jamais allés)     35
1                     Déjà allés     12
2  Pas intéressés (jamais allés)      7

In [8]:
df_xp_japan["percentage"] = (
    df_xp_japan["count"] / df_xp_japan["count"].sum() * 100
).round(2)

In [9]:
print(df_xp_japan)

                   been_to_Japan  count  percentage
0      Intéressés (jamais allés)     35       64.81
1                     Déjà allés     12       22.22
2  Pas intéressés (jamais allés)      7       12.96

Pie chart

In [10]:
fig = px.pie (
    df_xp_japan,
    values = "count",
    names = "been_to_Japan",
    title = "Un intérêt fort… mais une conversion faible",
    hole = 0
)

fig.update_traces (
    textinfo = "percent+label"
)

fig.update_layout (
    showlegend = True
)

Bar chart

In [11]:
fig = px.bar (
    df_xp_japan,
    x = "been_to_Japan",
    y = "percentage",
    text = "percentage",
    title = "Un intérêt fort… mais une conversion faible",
    color = "count"
)

fig.update_traces (
    texttemplate = "%{text}%",
    textposition="outside"
)

fig.update_layout (
    width=800,
    height=500,
    xaxis_title = "",
    yaxis_title = "Pourcentage de répondants",
    coloraxis_showscale=False
)

In [12]:
df_xp_japan["text_display"] = df_xp_japan["percentage"].astype(str) + "%"

df_xp_japan.loc[
    df_xp_japan["been_to_Japan"] == "Intéressés (jamais allés)",
    "text_display"
] = "<b>" + df_xp_japan["text_display"] + "</b>"

In [13]:
fig = px.bar (
    df_xp_japan,
    x = "been_to_Japan",
    y = "percentage",
    text = "text_display",
    title = "Un intérêt fort… mais une conversion faible",
    color = "been_to_Japan",
    color_discrete_map = {
        "Déjà allés": "#0C0241",
        "Pas intéressés (jamais allés)": "#0C0241",
        "Intéressés (jamais allés)": "#E6FF01"
        
    }
)

fig.update_traces (
    textfont = dict(size=14),
    textposition = "outside"
)

fig.update_layout (
    width=800,
    height=500,
    xaxis_title = "",
    yaxis_title = "Part des répondants (%)",
    showlegend = False
)

c:\Users\j-bal\anaconda3\Lib\site-packages\plotly\express\_core.py:1979: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

# Slide 3
## SEGMENTATION

filter df to keep only those 64%

📊 Tous les voyageurs intéressés par le Japon ne veulent pas la même chose.

Après avoir constaté un paradoxe clair  
👉 un intérêt très fort, mais une conversion faible,

la question suivante était simple :  
qu’est-ce qui est réellement ESSENTIEL pour ces voyageurs ?

🧠 Pour y répondre, je n’ai pas regardé des moyennes.  
J’ai analysé la part des répondants pour qui un critère est jugé “ESSENTIEL”.

Le résultat est sans ambiguïté :  
🍜 la gastronomie arrive largement en tête  
🌿 la nature et la randonnée suivent  
🏯 la culture et le patrimoine restent centraux

À l’inverse, le shopping, les événements ou les parcs à thème  
sont perçus comme secondaires par la majorité.

👉 Même niveau d’intérêt pour le Japon.  
👉 Mais des priorités très différentes.

💬 Dans vos analyses, regardez-vous ce qui est “important”…  
ou ce qui est réellement non négociable pour vos utilisateurs ?

In [14]:
mapping_interest = {
    "Not important at all": 0,
    "Slightly important": 1,
    "Moderately important": 2,
    "Very important": 3,
    "Essential": 4,
}

In [15]:
columns = [
    'rating_interest_culture_and_history', 
    'rating_interest_food', 
    'rating_interest_nature_hiking', 
    'rating_interest_shopping_and_techno',
    'rating_interest_events_and_festivals', 
    'rating_interest_wellness',
    'rating_interest_theme_park'
]

In [16]:
df_numeric = df.copy()

for col in columns:
    df_numeric[col] = df_numeric[col].map(mapping_interest)

In [17]:
label_map = {
    "rating_interest_culture_and_history": "Culture & History",
    "rating_interest_food": "Food",
    "rating_interest_nature_hiking": "Nature & Hiking",
    "rating_interest_shopping_and_techno": "Shopping & Tech",
    "rating_interest_events_and_festivals": "Events & Festivals",
    "rating_interest_wellness": "Wellness",
    "rating_interest_theme_park": "Theme Parks",
}

In [18]:

summary_df = (
    df_numeric[columns]
    .mean()
    .reset_index()
    .rename(columns = {
        "index": "interest",
        0: "value"
    })
)

summary_df["text_display"] = summary_df["value"].round(2)
summary_df["interest"] = summary_df["interest"].map(label_map)


fig_1 = px.bar (
    summary_df,
    x = "interest",
    y = "value",
    text = "text_display",
    title = "Un intérêt fort… mais une conversion faible",
)

fig_1.update_traces (
    textposition = "outside"
)

fig_1.update_layout (
    width=800,
    height=500,
    xaxis_title = "",
    yaxis_title = "Score moyen d’intérêt (0–4)"
)

In [19]:
essential_pct = []

for col in columns:
    pct = (df_numeric[col] == 4).mean() * 100
    essential_pct.append({
        "interest": col.replace("rating_interest_", "").replace("_", " ").title(),
        "essential_pct": round(pct, 1)
    })

essential_df = pd.DataFrame(essential_pct).sort_values(
    "essential_pct", ascending=False
)

essential_df

               interest  essential_pct
1                  Food           44.4
2         Nature Hiking           29.6
0   Culture And History           25.9
5              Wellness           11.1
3   Shopping And Techno            9.3
4  Events And Festivals            3.7
6            Theme Park            3.7

In [20]:
essential_df["text_display"] = essential_df["essential_pct"].astype(str) + "%"


essential_df = essential_df.sort_values(
    "essential_pct", ascending=False
).reset_index(drop=True)

essential_df.loc[0, "text_display"] = "<b>" + essential_df.loc[0, "text_display"] + "</b>"

In [21]:
#essential_df["interest"] = essential_df["interest"].map(label_map)
mapping_interest = {
    "Food": "Gastronomie",
    "Nature Hiking": "Nature & randonnée",
    "Culture And History": "Culture & patrimoine",
    "Wellness": "Bien-être",
    "Shopping And Techno": "Shopping & technologie",
    "Events And Festivals": "Événements & festivals",
    "Theme Park": "Parcs à thème"
}

essential_df["interest"] = (essential_df["interest"].map(mapping_interest))

In [22]:
fig = px.bar(
    essential_df,
    x="interest",
    y="essential_pct",
    text="text_display",
    title="Critères jugés ESSENTIELS par les voyageurs intéressés par le Japon (%)",
    color = "interest",
    color_discrete_map = {
        "Gastronomie": "#E6FF01",
        "Nature & randonnée": "#E9A107",
        "Culture & patrimoine": "#E9A107",
        "Bien-être": "#0C0241",
        "Shopping & technologie": "#0C0241",
        "Événements & festivals": "#313131",
        "Parcs à thème": "#313131"
        }
)

fig.update_traces(textfont = dict(size=15), textposition="outside")
fig.update_layout(
    width=800,
    height=500,
    xaxis_title="",
    yaxis_title="Part des répondants (%)",
    yaxis_range=[0, max(essential_df["essential_pct"]) * 1.2],
    showlegend = False
)

fig.show()

c:\Users\j-bal\anaconda3\Lib\site-packages\plotly\express\_core.py:1979: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

# Slide 4
## FREINS STRUCTURELS & FRICTION

filter df to keep only those 64%

🚧 Si l’intérêt est fort, pourquoi la conversion reste-t-elle faible ?

Après avoir identifié ce qui motive réellement les voyageurs,  
il restait une question clé :

👉 Qu’est-ce qui freine concrètement le passage à l’action ?

🧠 L’analyse montre un résultat très clair :  
la barrière principale n’est ni le budget, ni la popularité,  
mais la LANGUE.

Et ce point est crucial :  
ce frein persiste quel que soit le niveau d’expérience.  
Même chez les personnes déjà allées au Japon.

👉 L’expérience réduit certaines frictions…  
👉 mais n’élimine pas les freins structurels.

Autrement dit :  
le problème n’est pas un manque d’envie,  
mais un manque de réassurance.

💬 Dans vos projets data, combien de “freins” identifiés  
sont en réalité structurels plutôt que temporaires ?

In [23]:
display(df.head())

,Horodateur,nationality,country,age_group,family_situation,household_income_in_€,travel_frequency,been_to_Japan,Japan_vac_duration,rating_interest_culture_and_history,...,Japan_most_difficulties_1,Japan_most_difficulties_2,Japan_most_difficulties_3,Japan_most_difficulties_4,Japan_most_difficulties_5,alt_dest_most_difficulties_1,alt_dest_most_difficulties_2,alt_dest_most_difficulties_3,alt_dest_most_difficulties_4,alt_dest_most_difficulties_5
0,05/10/2025 13:09:39,France,France,35-44,Married_no_kids,1500-1999,Every 2–3 years,Déjà allés,More than 4 weeks,Essential,...,Language,Crowded/Popularity,Translation,NaN,NaN,Language,Transportation,Car rental,NaN,NaN
1,06/10/2025 13:30:50,France,France,45-54,Relationship_with_kids,1500-1999,Every 2–3 years,Intéressés (jamais allés),2 weeks,Essential,...,Language,Expensive,Translation,NaN,NaN,Expensive,Crowded,Translation,NaN,NaN
2,06/10/2025 17:20:05,France,France,35-44,Single,1500-1999,Once a year,Intéressés (jamais allés),3 weeks,Very important,...,Language,Car rental,Expensive,NaN,NaN,Language,Car rental,Expensive,NaN,NaN
3,06/10/2025 19:47:27,France,France,45-54,Single,2000-2499,Every 2–3 years,Intéressés (jamais allés),1 week,Moderately important,...,Car rental,Expensive,NaN,NaN,NaN,Transportation,NaN,NaN,NaN,NaN
4,06/10/2025 20:56:00,France,France,45-54,Married_no_kids,2500-2999,Every 2–3 years,Intéressés (jamais allés),3 weeks,Very important,...,Language,Expensive,NaN,NaN,NaN,Language,NaN,NaN,NaN,NaN

In [ ]:
df

In [31]:
df_difficulties = df[["Japan_most_difficulties_1", "Japan_most_difficulties_2", "Japan_most_difficulties_3", "Japan_most_difficulties_4", "Japan_most_difficulties_5"]]

In [32]:
df_difficulties

,Japan_most_difficulties_1,Japan_most_difficulties_2,Japan_most_difficulties_3,Japan_most_difficulties_4,Japan_most_difficulties_5
0,Language,Crowded/Popularity,Translation,NaN,NaN
1,Language,Expensive,Translation,NaN,NaN
2,Language,Car rental,Expensive,NaN,NaN
3,Car rental,Expensive,NaN,NaN,NaN
4,Language,Expensive,NaN,NaN,NaN
5,Language,NaN,NaN,NaN,NaN
6,Car rental,Expensive,Crowded/Popularity,NaN,NaN
7,Expensive,Crowded/Popularity,Translation,NaN,NaN
8,Language,Translation,NaN,NaN,NaN
9,Language,NaN,NaN,NaN,NaN
10,Language,Expensive,Crowded/Popularity,NaN,NaN
11,Crowded/Popularity,NaN,NaN,NaN,NaN
12,Expensive,NaN,NaN,NaN,NaN
13,Expensive,Crowded/Popularity,NaN,NaN,NaN
14,Car rental,Crowded/Popularity,Disaster,NaN,NaN
15,Language,Expensive,Translation,NaN,NaN
16,Language,Expensive,NaN,NaN,NaN
17,Expensive,Crowded/Popularity,Crowded/Popularity,NaN,NaN
18,Language,NaN,NaN,NaN,NaN
19,Language,Expensive,Crowded/Popularity,NaN,NaN
20,Language,Expensive,NaN,NaN,NaN
21,Car rental,Crowded/Popularity,Translation,NaN,NaN
22,Expensive,NaN,NaN,NaN,NaN
23,Language,Car rental,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN
25,Translation,NaN,NaN,NaN,NaN
26,Language,Transportation,Crowded/Popularity,NaN,NaN
27,Language,NaN,NaN,NaN,NaN
28,Transportation,Expensive,Crowded/Popularity,NaN,NaN
29,Language,Transportation,Car rental,NaN,NaN
30,Language,Expensive,Crowded/Popularity,NaN,NaN
31,Language,Translation,NaN,NaN,NaN
32,Language,Translation,NaN,NaN,NaN
33,Language,Expensive,Crowded/Popularity,NaN,NaN
34,Language,NaN,NaN,NaN,NaN
35,Language,Crowded/Popularity,Translation,Crowded/Popularity,NaN
36,Language,Expensive,NaN,NaN,NaN
37,Language,NaN,NaN,NaN,NaN
38,Language,NaN,NaN,NaN,NaN
39,Language,Expensive,Crowded/Popularity,NaN,NaN
40,Language,Expensive,Translation,NaN,NaN
41,Language,Expensive,NaN,NaN,NaN
42,Transportation,NaN,NaN,NaN,NaN
43,Crowded/Popularity,NaN,NaN,NaN,NaN
44,Crowded/Popularity,NaN,NaN,NaN,NaN
45,Language,Crowded/Popularity,Translation,NaN,NaN
46,Crowded/Popularity,NaN,NaN,NaN,NaN
47,Expensive,NaN,NaN,NaN,NaN
48,Language,Crowded/Popularity,Translation,NaN,NaN
49,Language,Expensive,NaN,NaN,NaN
50,Language,Transportation,Crowded/Popularity,NaN,NaN
51,Expensive,NaN,NaN,NaN,NaN
52,Expensive,NaN,NaN,NaN,NaN
53,Language,Crowded/Popularity,Translation,NaN,NaN